nixos-26.05 prep: remove bitwarden-desktop as it uses eol electron
fixes the following eval error that occurs when updating to nixos-26.05:

error: Refusing to evaluate package 'electron-39.8.10'