nixos-26.05 prep: add nvidia-kernel-modules to allowUnfreePredicate
fixes the following eval error that occurs when updating to nixos-26.05:

error: Refusing to evaluate package 'nvidia-kernel-modules-595.71.05-6.18.33'