nixos-26.05 prep: remove unmaintained neofetch, add hyfetch
we already have fastfetch but im adding hyfetch since its a good edition and
should have already been added.

fixes the following error that occurs when updating to nixos-26.05:

error: 'neofetch' has been removed because it was unmaintained upstream.
Consider using the updated fork 'neowofetch' provided by the 'hyfetch' package
or the alternative 'fastfetch' instead.